package com.zillion.qa.vspnprogramadmin;

public interface OR 
{
	public final String PROVIDER_URL_ADD_PATIENT_LAST_STAGE="//button[text()='ADD PATIENT']";
	public final String PROVIDER_URL_ALERTMSG_1STNAME_REQUIRED="//p[text()='Your First Name Is Required.']";
	public final String PROVIDER_URL_ALERTMSG_LASTNAME_REQUIRED="//p[text()='Your Last Name Is Required.']";
	public final String PROVIDER_URL_ALERTMSG_EMAIL_REQUIRED="//span[text()='Your email is required.']";
	public final String PROVIDER_URL_ALERTMSG_CONFIRMEMAIL_REQUIRED="//span[text()='You must confirm your email address.']";
	public final String PROVIDER_URL_ALERTMSG_MONTH_REQUIRED="//span[text()='Month is required.']";
	public final String PROVIDER_URL_ALERTMSG_DATE_REQUIRED="//span[text()='Day is required.']";
	public final String PROVIDER_URL_ALERTMSG_YEAR_REQUIRED="//span[text()='Year is required.']";
	public final String PROVIDER_URL_ADD_PATIENT_FIRSTNAME_TEXTBOX="//input[@id='firstName']";
	public final String PROVIDER_URL_ADD_PATIENT_LASTNAME_TEXTBOX="//input[@id='lastName']";
	public final String PROVIDER_URL_ADD_PATIENT_EMAIL_TEXTBOX="//input[@id='email']";
	public final String PROVIDER_URL_ADD_PATIENT_CONFIRMEMAIL_TEXTBOX="//input[@id='confirmEmail']";
	public final String PROVIDER_URL_ADD_PATIENT_ADD_MONTH_FIELD="//select[@id='dobMonth']";
	public final String PROVIDER_URL_ADD_PATIENT_ADD_DAY_FIELD="//select[@id='dobDay']";
	public final String PROVIDER_URL_ADD_PATIENT_ADD_YEAR_FIELD="//select[@id='dobYear']";
	public final String PROVIDER_URL_ADD_PATIENT_ORGANIZATION_FIELD="//input[@id='selfOrganization']";
	public final String PROVIDER_URL_ADD_PATIENT_EMAIL_ADDRESS_NOTMATCH_MSG="//span[contains(text(),'email address do not match')]";
	public final String PROVIDER_URL_ADD_PATIENT_FINALSTAGE_BUTTON="//button[text()='ADD PATIENT']";
	public final String PROVIDER_URL_ADD_PATIENT_COUNT="//span[@class='page-header-counter-number align-middle ng-binding ng-scope']";
	public final String PROVIDER_URL_ADD_PATIENT_AGE_LIMIT="//span[contains(text(),'Oops! Sorry, members must be at least 18 years of age to participate in the program.')]";	
	public final String FIRSTNAME_LABEL="//span[contains(text(),'First Name *')]";
	public final String LASTNAME_LABEL="//span[contains(text(),'Last Name *')]";
	public final String EMAIL_LABEL="//span[contains(text(),'Email *')]";
	public final String CONFIRMEMAIL_LABEL="//span[contains(text(),'Confirm Email *')]";
	public final String DOB_LABEL="//span[contains(text(),'Date of Birth *')]";
	public final String ORGANIZATION_LABEL="//span[contains(text(),'Organization *')]";
	public final String CLOSE_ICON ="//a[@ng-click='close()']";
	public final String ORGANIZATION="//select[@name='organization']";
	public final String PROVIDER_PHYSICIAN_IS_REQUIRED_ERROR_MSG="//span[contains(text(),'Physician is required')]";
	public final String PROVIDER_PHYSICIAN_LABEL="//span[contains(text(),'Physician')]";
	public final String PROVIDER_PHYSICIAN_DROPDOWN="//select[@name='physician']";
	public final String PROVIDER_URL_ADD_PATIENT_PROGRAM_FIELD="//span[contains(text(),'Programs ')]//following::select";
	public final String PROGRAM_LABEL="//span[contains(text(),'Programs ')]";
	public final String PROVIDER_PROGRAM_IS_REQUIRED_ERROR_MSG="//span[contains(text(),'Program is required.')]";
	public final String PRACTITIONER_LOGIN_PATIENT_TAB_TEXT_REF="//div[@id='navbarPrimaryInner']//a//span[text()='Patients']";
	public final String PROVIDER_URL_ADD_PATIENT_BUTTON ="//button[@id='addNewMember']";
	public final String ADD_PATIENT_TEXT_INLEFT_CORNER="//span[text()='Add Patient']";
	public final String PATIENT_HAS_BEEN_ADDED_SUCCESSFULLY_OK_BUTTON="//div[@class='modal-content']//button[contains(text(),'OK')]";
	public final String GUERRILLA_MAIL_DROPDOWN="//select[@id='gm-host-select']";
	public final String GUERRILLA_MAIL_TEXTBOX="//span//input[@type='text']";
	public final String GUERRILLA_MAIL_SET_BUTTON="//button[contains(text(),'Set')]";
	public final String GUERRILLA_MAIL_ACTIVATE_YOUR_ACCOUNT_LINK="";
	public final String GUERRILLA_MAIL_EDIT_BUTTON="//span[@id='inbox-id']";
	public final String GUERRILLA_MAIL_CONGRATULATION_MESSAGE="//div[contains(text(),'Congratulations! You have completed your Registration successfully.')]";
	public final String GUERRILLA_MAIL_WELCOME_MESSAGE_VSPN="//td[contains(.,'Welcome to your VSPN Patient Journey')]";
	public final String GUERRILLA_MAIL_GENERATED_LINK_VSPN="//a[contains(text(),'Click here to complete your remaining enrollment process')]";
	public final String GUERRILLA_MAIL_COMPLETE_LINK="//td[contains(.,'Registration complete')]";
	public final String PARTITIONER_YOP_EMAIL_TEXTBOX="//input[@id='login']"; 
	public final String PARTITIONER_YOP_EMAIL_CHECKBOX="//input[@type='submit']"; 
	public final String PARTITIONER_YOP_EMAIL_IFRAME="//iframe[@id='ifmail']";
	public final String PARTITIONER_YOP_EMAIL_GENERATED_LINK="//a[contains(text(),'Click here to complete your remaining enrollment process')]";
	public final String  YOP_EMAIL_TEXTBOX="//input[@id='login']"; 
	public final String YOP_EMAIL_CHECK_INBOX="//input[@type='submit']"; 
	public final String YOP_EMAIL_IFRAME="//html/body/div[5]/table/tbody/tr[1]/td/table/tbody/tr/td[1]/table/tbody/tr[2]/td/iframe";
	public final String ORBERA_COACH_1on1_MAIL="//*[@id='m1']//span[contains(text(),'1-on-1 Session Rescheduled')]";
	public final String ORBERA_COACH_1on1_MAIL_GR="//tbody//tr//td[3]";
	public final String ORBERA_COACH_1on1_CONTENT="//div[contains(text(),'The 1-on-1 session you were scheduled')]";
	public final String YOP_EMAIL_IFRAME1="//html/body/div[5]/table/tbody/tr[1]/td/table/tbody/tr/td[1]/table/tbody/tr[2]/td/iframe";
	public final String YOP_EMAIL_IFRAME2="//html/body/div[5]/table/tbody/tr[1]/td/table/tbody/tr/td[2]/table/tbody/tr[2]/td[1]/iframe";
	public final String ORBERA_COACH_1on1_CANCELlATION_MAIL="//*[@id='m1']//span[contains(text(),'Session Canceled')]";
	public final String ORBERA_COACH_1on1_CANCELLATION_CONTENT="//div[contains(text(),'has been canceled')]";
	public final String ORBERA_COACH_1on1_MAIL_SCHEDULED="//*[@id='m1']//*[contains(text(),'Session Scheduled: 1-on-1')]";
	public final String ORBERA_COACH_1on1_CONTENT_SCHEDULED="//div[contains(@id,'mail')]//*[contains(text(),'scheduled to conduct a 1-on-1 session')]";
	public final String GUERRILLA_MAIL_INBOX_BUTTON="//a[@id='back_to_inbox_link']";
	public final String GUERRILLA_MAIL_EMAIL_CHECKBOX="//tbody//tr/td[1]//input[@type='checkbox']";
	public final String GUERRILLA_MAIL_DELETE_BUTTON="//input[@id='del_button']";
	public final String GUERRILLA_MAIL_1ON1_SCHEDULED_LINK="//td[contains(text(),'Your 1on1 Session Has been Scheduled')]";
	public final String GUERRILLA_MAIL_1ON1_SCHEDULED_LINK_CONTENT="//*[contains(text(),'This message is to confirm your 1on1 Session')]";
}
